import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer, Navbar } from '@/components/shared';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='dark' lang='en'>
      <body
        className={`container min-h-dvh space-y-5 py-5 dark:bg-dark-light dark:text-white ${inter.className}`}
      >
        <Navbar />
        <main className='space-y-5'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
